apiVersion: v1
kind: Namespace
metadata:
  name: ai-cyber-lab
  labels:
    name: ai-cyber-lab
    purpose: educational-cybersecurity
    version: "1.0.0"
  annotations:
    description: "AI-Augmented Cyber Lab for cloud-native security education"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-cyber-lab-quota
  namespace: ai-cyber-lab
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16" 
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-cyber-lab-network-policy
  namespace: ai-cyber-lab
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ai-cyber-lab
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: ai-cyber-lab
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
